"""Create the ReconAI domain schema.

Revision ID: 20260824_0001
Revises:
Create Date: 2026-08-24
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "20260824_0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("name", sa.String(150), nullable=False), sa.Column("role", sa.String(30), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.create_table("import_batches", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("filename", sa.String(255), nullable=False), sa.Column("source_type", sa.String(50), nullable=False), sa.Column("uploaded_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("file_hash", sa.String(64)), sa.Column("record_count", sa.Integer()), sa.Column("valid_count", sa.Integer()), sa.Column("error_count", sa.Integer()), sa.Column("status", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("completed_at", sa.DateTime(timezone=True)))
    op.create_table("reconciliation_runs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("started_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("invoice_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("payment_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("auto_matched_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("review_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("unmatched_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("exception_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("status", sa.String(30), nullable=False), sa.Column("engine_version", sa.String(50)), *(sa.CheckConstraint(f"{name} >= 0", name=f"ck_runs_{name}_nonnegative") for name in ("invoice_count", "payment_count", "auto_matched_count", "review_count", "unmatched_count", "exception_count")))
    op.create_table("invoices", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("invoice_number", sa.String(100), nullable=False), sa.Column("customer_name", sa.String(255), nullable=False), sa.Column("normalized_customer", sa.String(255)), sa.Column("invoice_date", sa.Date(), nullable=False), sa.Column("due_date", sa.Date()), sa.Column("total_amount", sa.Numeric(18, 2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("source_batch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("import_batches.id")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.CheckConstraint("total_amount >= 0", name="ck_invoices_total_amount_nonnegative"), sa.UniqueConstraint("invoice_number", "currency", name="uq_invoices_number_currency"))
    op.create_index("ix_invoices_invoice_number", "invoices", ["invoice_number"]); op.create_index("ix_invoices_normalized_customer", "invoices", ["normalized_customer"]); op.create_index("ix_invoices_status", "invoices", ["status"]); op.create_index("ix_invoices_due_date", "invoices", ["due_date"])
    op.create_table("payments", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("transaction_reference", sa.String(150)), sa.Column("payer_name", sa.String(255), nullable=False), sa.Column("normalized_payer", sa.String(255)), sa.Column("payment_date", sa.Date(), nullable=False), sa.Column("amount", sa.Numeric(18, 2), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("bank_account", sa.String(100)), sa.Column("description", sa.Text()), sa.Column("source_batch_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("import_batches.id")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.CheckConstraint("amount >= 0", name="ck_payments_amount_nonnegative"))
    op.create_index("ix_payments_transaction_reference", "payments", ["transaction_reference"]); op.create_index("ix_payments_normalized_payer", "payments", ["normalized_payer"]); op.create_index("ix_payments_payment_date", "payments", ["payment_date"])
    op.create_table("reconciliation_candidates", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("reconciliation_runs.id"), nullable=False), sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=False), sa.Column("invoice_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("invoices.id"), nullable=False), sa.Column("score", sa.Numeric(5, 2)), sa.Column("decision", sa.String(30)), sa.Column("amount_score", sa.Numeric(5, 2)), sa.Column("customer_score", sa.Numeric(5, 2)), sa.Column("reference_score", sa.Numeric(5, 2)), sa.Column("date_score", sa.Numeric(5, 2)), sa.Column("currency_score", sa.Numeric(5, 2)), sa.Column("history_score", sa.Numeric(5, 2)), sa.Column("score_gap", sa.Numeric(5, 2)), sa.Column("explanation", postgresql.JSONB()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), *(sa.CheckConstraint(f"{name} >= 0 AND {name} <= 100", name=f"ck_candidates_{name}_range") for name in ("score", "amount_score", "customer_score", "reference_score", "date_score", "currency_score", "history_score", "score_gap")))
    op.create_index("ix_candidates_payment_id", "reconciliation_candidates", ["payment_id"]); op.create_index("ix_candidates_invoice_id", "reconciliation_candidates", ["invoice_id"]); op.create_index("ix_candidates_run_id", "reconciliation_candidates", ["run_id"])
    op.create_table("reconciliation_allocations", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("reconciliation_runs.id"), nullable=False), sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=False), sa.Column("invoice_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("invoices.id"), nullable=False), sa.Column("allocated_amount", sa.Numeric(18, 2), nullable=False), sa.Column("method", sa.String(30), nullable=False), sa.Column("confidence_score", sa.Numeric(5, 2)), sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.CheckConstraint("allocated_amount > 0", name="ck_allocations_amount_positive"), sa.CheckConstraint("confidence_score >= 0 AND confidence_score <= 100", name="ck_allocations_confidence_score_range"))
    op.create_index("ix_allocations_payment_id", "reconciliation_allocations", ["payment_id"]); op.create_index("ix_allocations_invoice_id", "reconciliation_allocations", ["invoice_id"]); op.create_index("ix_allocations_run_id", "reconciliation_allocations", ["run_id"])
    op.create_table("exceptions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("reconciliation_runs.id")), sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id")), sa.Column("invoice_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("invoices.id")), sa.Column("allocation_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("reconciliation_allocations.id")), sa.Column("type", sa.String(50), nullable=False), sa.Column("severity", sa.String(20), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("status", sa.String(30), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")), sa.Column("resolved_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("resolution", sa.Text()))
    op.create_index("ix_exceptions_status", "exceptions", ["status"]); op.create_index("ix_exceptions_severity", "exceptions", ["severity"]); op.create_index("ix_exceptions_run_id", "exceptions", ["run_id"])
    op.create_table("audit_logs", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("action", sa.String(50), nullable=False), sa.Column("entity_type", sa.String(50), nullable=False), sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("old_values", postgresql.JSONB()), sa.Column("new_values", postgresql.JSONB()), sa.Column("description", sa.Text()), sa.Column("ip_address", sa.String(45)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")))
    op.create_index("ix_audit_logs_entity_type_entity_id", "audit_logs", ["entity_type", "entity_id"]); op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"])


def downgrade() -> None:
    for table in ("audit_logs", "exceptions", "reconciliation_allocations", "reconciliation_candidates", "payments", "invoices", "reconciliation_runs", "import_batches", "users"):
        op.drop_table(table)
